### ISSUE TITLE
关于bypass问题

### ISSUE THREAD

**Issue by xiaonian233** [luciouskami/APEX-EACBypass#1]
您好，表示已经根据您的描述重命名以及谢了空的dll也已经成功载入进了游戏
![image](https://user-images.githubusercontent.com/21072615/53676738-8947c100-3ce1-11e9-9b9d-c496567a59a1.png)
但是仍然会
![image](https://user-images.githubusercontent.com/21072615/53676716-50a7e780-3ce1-11e9-874d-65f9d4468e1a.png)
作者关于这个空dll有什么要求吗？

**Comment by luciouskami** [comment]
伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。

**Comment by xiaonian233** [comment]
> 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。

好明白了我去尝试

**Comment by xiaonian233** [comment]
> 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。

您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败

**Comment by luciouskami** [comment]
> > 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> > 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。
> 
> 您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败

因为我这个方法是两个版本以前，可能他心跳加了别的检测，我现在都是带上驱动调试。心跳的问题，还需要继续调试才能过掉。

**Comment by xiaonian233** [comment]
> > > 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> > > 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。
> > 
> > 
> > 您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败
> 
> 因为我这个方法是两个版本以前，可能他心跳加了别的检测，我现在都是带上驱动调试。心跳的问题，还需要继续调试才能过掉。

好吧作者加油期待新进展

**Comment by luciouskami** [comment]
> > > > 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> > > > 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。
> > > 
> > > 
> > > 您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败
> > 
> > 
> > 因为我这个方法是两个版本以前，可能他心跳加了别的检测，我现在都是带上驱动调试。心跳的问题，还需要继续调试才能过掉。
> 
> 好吧作者加油期待新进展

其实我跟倾向于带着驱动跑，代码等忙完了会传的，都是很简单的东西。

**Comment by xiaonian233** [comment]
> > > > > 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> > > > > 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。
> > > > 
> > > > 
> > > > 您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败
> > > 
> > > 
> > > 因为我这个方法是两个版本以前，可能他心跳加了别的检测，我现在都是带上驱动调试。心跳的问题，还需要继续调试才能过掉。
> > 
> > 
> > 好吧作者加油期待新进展
> 
> 其实我跟倾向于带着驱动跑，代码等忙完了会传的，都是很简单的东西。

好的！期待

**Comment by luciouskami** [comment]
> > > > > > 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> > > > > > 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。
> > > > > 
> > > > > 
> > > > > 您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败
> > > > 
> > > > 
> > > > 因为我这个方法是两个版本以前，可能他心跳加了别的检测，我现在都是带上驱动调试。心跳的问题，还需要继续调试才能过掉。
> > > 
> > > 
> > > 好吧作者加油期待新进展
> > 
> > 
> > 其实我跟倾向于带着驱动跑，代码等忙完了会传的，都是很简单的东西。
> 
> 好的！期待

代码已经上传@xiaonian233
https://github.com/luciouskami/AnotherApexDebug

**Comment by xiaonian233** [comment]
> 伪造的dll必须要导出他的全部接口（哪怕并没有使用），具体怎么写可以参考eac的sdk，里面有函数原型。
> 当然，现在游戏有了检测，最好的方法还是带着驱动去跑，过调试的方法我也已经说了，如果还不会的话，过两天会上传一份代码。
> 
> 您好作者我这里还是不行，我把接口写了还是会失败，我直接注入它原本的那个dll也是会失败
> 
> 因为我这个方法是两个版本以前，可能他心跳加了别的检测，我现在都是带上驱动调试。心跳的问题，还需要继续调试才能过掉。
> 
> 好吧作者加油期待新进展
> 
> 其实我跟倾向于带着驱动跑，代码等忙完了会传的，都是很简单的东西。
> 
> 好的！期待
> 
> 代码已经上传@xiaonian233
> https://github.com/luciouskami/AnotherApexDebug

啊非常感谢
